### PR TITLE
Webzero main events

### PR DESCRIPTION
**Pull request by TriplEight**
add events:
- pizza dao
- fuel $ frens
- Just opensource
- zkSync & crypto girls club

### CODE REVIEW

**Comment by kuzdogan** [comment]
Hey this is really confusing. I see you want to add:
- Bitcoin Pizza party
- Fuel and Friends

but these event already exist on the website. What do you want to do? 
- Open data brunch with Subsquid
- Fueling Emerging technologies
- zkspäti

**Comment by TriplEight** [comment]
@kuzdogan thanks for looking into it.

> Bitcoin Pizza party

i failed to find Pizza DAO event on https://blockchainweek.berlin/24/events

> Fuel and Friends

it's not the same as https://blockchainweek.berlin/24/event/subsquid, you can check here: https://lu.ma/joinwebzero

**Comment by TriplEight** [comment]
@kuzdogan anything else or let's merge it?

**Comment by kuzdogan** [comment]
Ok this has been really difficult to understand, the fact that you're trying to add the same events on multiple PRs is not really helping, but here's what I did:

I've added these: 
- Bitcoin pizza event
- Fuel and Friends
- Open data brunch
- All coworking days 21 to 24th

Also fixed the dates and other info for:
-  Subsquid & Fuel brunch

Now these two events already exist on the website and were added by someone else. Do you really want to change it and why?
- Fueling Emerging technologies
- zkspäti

Please double check carefully if everything is correct on the website https://blockchainweek.berlin/24 and let me know what you want to do with the events that are already on the website.

**Comment by TriplEight** [comment]
yeah I got you @kuzdogan thanks, those commits were too many changes at once and I couldn't find the existing events created by someone else.
Now I found them: https://github.com/blockchainweek/data/pull/107

**Pull request closed without merging**
